// ============================================================
// languages.js — Centralized i18n dictionary
// Primary: Burmese (Myanmar) | Secondary: English
// ============================================================

const LANGUAGES = {
  my: {
    // ---- Navigation ----
    nav_home: "ပင်မ",
    nav_login: "ဝင်ရောက်ရန်",
    nav_register: "စာရင်းသွင်းရန်",
    nav_dashboard: "ဒက်ရှ်ဘုတ်",
    nav_jobs: "အလုပ်များ",
    nav_logout: "ထွက်ရန်",
    nav_admin: "Admin",

    // ---- Home / Hero ----
    hero_title: "Myanmar Freelance Escrow",
    hero_subtitle: "အလုပ်ချိတ်ဆက်မှုနှင့် ဘဏ္ဍာရေးလုံခြုံမှုအတွက် ယုံကြည်စိတ်ချရသော ပလက်ဖောင်း",
    hero_tagline: "Freelancer များနှင့် Hiring Manager များအတွက် လုံခြုံသော Escrow စနစ်",
    hero_cta_register: "အခုပဲ စာရင်းသွင်းပါ",
    hero_cta_login: "ဝင်ရောက်ပါ",
    hero_how_title: "ဘယ်လိုအလုပ်လုပ်လဲ",
    hero_how_1: "စာရင်းသွင်းပြီး အလုပ်တင်ပါ / အဆိုပြုပါ",
    hero_how_2: "ဒီဂျစ်တယ်စာချုပ်ချုပ်ပါ",
    hero_how_3: "Escrow ငွေသွင်းပြီး အလုပ်စတင်ပါ",
    hero_how_4: "Milestone ပြီးဆုံးပါက ငွေထုတ်ပေးပါ",
    hero_features_title: "ဘာကြောင့် ရွေးချယ်သင့်လဲ",
    hero_feature_1_title: "Escrow လုံခြုံရေး",
    hero_feature_1_desc: "ငွေကို Admin က စီမံခန့်ခွဲပြီး နှစ်ဦးစလုံးအတွက် ကာကွယ်မှုပေးပါတယ်",
    hero_feature_2_title: "ဒေသတွင်း ငွေပေးချေမှု",
    hero_feature_2_desc: "KBZ Pay, Wave Pay, USDT အပါအဝင် ဒေသတွင်း ငွေပေးချေမှုနည်းလမ်းများ",
    hero_feature_3_title: "မြန်မာဘာသာ",
    hero_feature_3_desc: "မြန်မာဘာသာဖြင့် အပြည့်အစုံ အသုံးပြုနိုင်ပါတယ်",
    hero_feature_4_title: "စာချုပ်စာတမ်း",
    hero_feature_4_desc: "ဒီဂျစ်တယ် လက်မှတ်ဖြင့် စာချုပ်ချုပ်ဆိုပါ",
    hero_stats_jobs: "အလုပ်များ",
    hero_stats_users: "အသုံးပြုသူများ",
    hero_stats_released: "ငွေထုတ်ပေးပြီး",
    hero_stats_trust: "ယုံကြည်မှု",

    // ---- Auth ----
    auth_login_title: "ဝင်ရောက်ရန်",
    auth_register_title: "စာရင်းသွင်းရန်",
    auth_email: "အီးမေးလ်",
    auth_password: "လျှို့ဝှက်နံပါတ်",
    auth_confirm_password: "လျှို့ဝှက်နံပါတ် အတည်ပြုရန်",
    auth_name: "အမည်",
    auth_role_title: "ဘယ်အနေအထားနဲ့ ဝင်မလဲ",
    auth_role_freelancer: "ဝန်ဆောင်မှုပေးမယ် (Freelancer)",
    auth_role_hiring: "ဝန်ဆောင်မှုယူမယ် (Hiring)",
    auth_role_freelancer_desc: "သင့်ကျွမ်းကျင်မှုဖြင့် အလုပ်လုပ်ပြီး ငွေရှာပါ",
    auth_role_hiring_desc: "သင့်စီမံကိန်းအတွက် Freelancer များငှားပါ",
    auth_skill_level: "ကျွမ်းကျင်မှုအဆင့်",
    auth_skill_beginner: "အစမ်းသင်",
    auth_skill_entry: "အခြေခံ",
    auth_skill_mid: "အလယ်အတန်",
    auth_skill_advanced: "အဆင့်မြင့်",
    auth_skill_pro: "ပရော်ဖက်ရှင်နယ်",
    auth_submit_login: "ဝင်ရောက်ရန်",
    auth_submit_register: "စာရင်းသွင်းရန်",
    auth_no_account: "စာရင်းမရှိသေးဘူးလား",
    auth_has_account: "စာရင်းရှိပြီးသားလား",
    auth_role_locked_warning: "⚠️ Role ကို စာရင်းသွင်းပြီးနောက် ပြောင်းလဲမရပါ",
    auth_error_password_mismatch: "လျှို့ဝှက်နံပါတ် မတူပါ",
    auth_error_weak_password: "လျှို့ဝှက်နံပါတ် အားနည်းပါသည် (အနည်းဆုံး ၆ လုံး)",
    auth_error_email_in_use: "ဤအီးမေးလ်ဖြင့် စာရင်းသွင်းပြီးပြီ",
    auth_error_invalid_email: "အီးမေးလ် မှားနေပါသည်",
    auth_error_user_not_found: "ဤအသုံးပြုသူကို ရှာမတွေ့ပါ",
    auth_error_wrong_password: "လျှို့ဝှက်နံပါတ် မှားနေပါသည်",

    // ---- Dashboard ----
    dash_welcome: "ကြိုဆိုပါတယ်",
    dash_freelancer_title: "Freelancer Dashboard",
    dash_hiring_title: "Hiring Dashboard",
    dash_my_proposals: "ကျွန်တော့်အဆိုပြုချက်များ",
    dash_active_contracts: "Active စာချုပ်များ",
    dash_wallet: "ပိုက်ဆံအိတ်",
    dash_balance: "လက်ကျန်",
    dash_pending_withdrawals: "ထုတ်ယူဆဲ",
    dash_posted_jobs: "တင်ထားသည့်အလုပ်များ",
    dash_incoming_proposals: "ဝင်ရောက်လာသည့်အဆိုပြုချက်များ",
    dash_manage_escrow: "Escrow စီမံရန်",
    dash_total_earned: "စုစုပေါင်းရရှိ",
    dash_total_spent: "စုစုပေါင်းသုံးစွဲ",
    dash_no_proposals: "အဆိုပြုချက် မရှိသေးပါ",
    dash_no_contracts: "စာချုပ် မရှိသေးပါ",
    dash_no_jobs: "အလုပ် မတင်ရသေးပါ",
    dash_view_details: "အသေးစိတ်ကြည့်ရန်",

    // ---- Jobs ----
    jobs_title: "အလုပ်များ",
    jobs_post_new: "အသစ်တင်ရန်",
    jobs_search_placeholder: "အလုပ်ရှာဖွေရန်...",
    jobs_budget: "ဘတ်ဂျက်",
    jobs_milestones: "Milestones",
    jobs_status_open: "ဖွင့်ထားသည်",
    jobs_status_interviewing: "အင်တာဗျူးဆဲ",
    jobs_status_escrow_pending: "Escrow စောင့်ဆိုင်း",
    jobs_status_active: "Active",
    jobs_status_completed: "ပြီးဆုံး",
    jobs_status_disputed: "အငြင်ပွား",
    jobs_proposal_count: "အဆိုပြုချက်",
    jobs_apply: "လျှောက်ထားရန်",
    jobs_details: "အသေးစိတ်",
    jobs_post_title: "အလုပ်အမည်",
    jobs_post_desc: "အသေးစိတ်ဖော်ပြချက်",
    jobs_post_budget: "ဘတ်ဂျက် (MMK)",
    jobs_post_milestones: "Milestone အရေအတွက် (အများဆုံး ၅)",
    jobs_post_submit: "အလုပ်တင်ရန်",
    jobs_post_cancel: "ပယ်ဖျက်ရန်",
    jobs_proposal_bid: "ကမ်းလှမ်းငွေ (MMK)",
    jobs_proposal_cover: "ဖုံးအုပ်စာ",
    jobs_proposal_submit: "အဆိုပြုရန်",
    jobs_accept: "လက်ခံရန်",
    jobs_reject: "ပယ်ချရန်",

    // ---- Escrow ----
    escrow_title: "Escrow ငွေပေးချေမှု",
    escrow_select_milestone: "Milestone ရွေးပါ",
    escrow_amount: "ငွေပမာဏ (MMK)",
    escrow_payment_method: "ငွေပေးချေမှုနည်းလမ်း",
    escrow_wallets: "Mobile Wallets",
    escrow_banks: "ဘဏ်များ",
    escrow_digital: "ဒီဂျစ်တယ် စနစ်များ",
    escrow_kbz: "KBZ Pay",
    escrow_wave: "Wave Pay",
    escrow_aya_pay: "AYA Pay",
    escrow_cb_pay: "CB Pay",
    escrow_uab_pay: "UAB Pay",
    escrow_yoma: "Yoma Bank",
    escrow_aya_bank: "AYA Bank",
    escrow_kbz_bank: "KBZ Bank",
    escrow_cb_bank: "CB Bank",
    escrow_usdt: "USDT (TRC-20)",
    escrow_binance: "Binance Pay",
    escrow_djo: "DJO Pay",
    escrow_upload_proof: "Transaction ID / Screenshot တင်ရန်",
    escrow_submit_payment: "ပေးချေမှု အတည်ပြုရန်",
    escrow_status_pending: "စောင့်ဆိုင်းဆဲ",
    escrow_status_secured: "ငွေအာမခံပြီး",
    escrow_status_released: "ငွေထုတ်ပေးပြီး",
    escrow_status_disputed: "အငြင်ပွားဆဲ",
    escrow_verify: "Admin အတည်ပြုရန်",
    escrow_file_placeholder: "Transaction ID သို့မဟုတ် Screenshot တင်ပါ",

    // ---- Contract ----
    contract_title: "ဒီဂျစ်တယ် စာချုပ်",
    contract_job: "အလုပ်",
    contract_parties: "ပါဝင်သူများ",
    contract_client: "Hiring Manager",
    contract_freelancer: "Freelancer",
    contract_milestones_title: "Milestone အသေးစိတ်",
    contract_sign: "လက်မှတ်ရေးထိုးရန်",
    contract_sign_placeholder: "သင့်အမည် ရိုက်ထည့်ပါ",
    contract_sign_btn: "စာချုပ်ချုပ်ဆိုရန်",
    contract_signed: "လက်မှတ်ရေးထိုးပြီး",
    contract_awaiting_escrow: "Escrow စောင့်ဆိုင်းဆဲ",
    contract_fully_signed: "နှစ်ဦးစလုံး လက်မှတ်ရေးထိုးပြီး",
    contract_not_signed: "လက်မှတ်မရေးရသေးပါ",
    contract_sign_warning: "⚠️ လက်မှတ်ရေးထိုးပြီးနောက် ပြန်ပြင်မရပါ",

    // ---- Workflow Status ----
    workflow_post: "အလုပ်တင်",
    workflow_interview: "အင်တာဗျူး",
    workflow_contract: "စာချုပ်",
    workflow_escrow: "Escrow",
    workflow_active: "Active",
    workflow_release: "ထုတ်ပေး",

    // ---- Admin ----
    admin_title: "Admin Dashboard",
    admin_overview: "ခြုံငုံကြည့်ရန်",
    admin_all_jobs: "အလုပ်အားလုံး",
    admin_all_users: "အသုံးပြုသူအားလုံး",
    admin_pending_verifications: "အတည်ပြုစောင့်ဆိုင်းဆဲ",
    admin_disputes: "အငြင်ပွားမှုများ",
    admin_action: "လုပ်ဆောင်ရန်",
    admin_unlock_milestone: "Milestone ဖွင့်ရန်",
    admin_full_refund: "အပြည့်အဝ ပြန်အမ်းရန်",
    admin_fifty_fifty: "၅၀/၅၀ ခွဲဝေရန်",
    admin_full_release: "၁၀၀% Freelancer ထုတ်ပေးရန်",
    admin_reset_job: "အလုပ်ပြန်ဖွင့်ရန် (အခမဲ့)",
    admin_platform_fee: "Platform Fee",
    admin_fee_hiring: "Hiring: ၁%",
    admin_fee_freelancer: "Freelancer: ၂%",
    admin_total_revenue: "စုစုပေါင်း ဝင်ငွေ",

    // ---- Milestones ----
    milestone_title: "Milestone",
    milestone_status_pending: "စောင့်ဆိုင်းဆဲ",
    milestone_status_escrowed: "Escrow ထားပြီး",
    milestone_status_released: "ထုတ်ပေးပြီး",
    milestone_status_disputed: "အငြင်ပွားဆဲ",
    milestone_amount: "ငွေပမာဏ",
    milestone_progress: "တိုးတက်မှု",

    // ---- General ----
    general_save: "သိမ်းဆည်းရန်",
    general_cancel: "ပယ်ဖျက်ရန်",
    general_confirm: "အတည်ပြုရန်",
    general_back: "နောက်သို့",
    general_loading: "ခေါ်ယူနေသည်...",
    general_no_data: "ဒေတာမရှိပါ",
    general_error: "အမှားတစ်ခုဖြစ်ပွားပါသည်",
    general_success: "အောင်မြင်ပါသည်",
    general_close: "ပိတ်ရန်",
    general_language: "ဘာသာစကား",
    general_myanmar: "မြန်မာ",
    general_english: "English",
    general_currency: "MMK",
    general_platform_name: "MM Escrow",
    general_version: "v1.0",
    general_made_with: "Myanmar Freelancers အတွက် ဖန်တီးထားပါသည်",
    general_trust_badge: "🔒 လုံခြုံပြီး ယုံကြည်စိတ်ချရသည်",
  },

  en: {
    // ---- Navigation ----
    nav_home: "Home",
    nav_login: "Login",
    nav_register: "Register",
    nav_dashboard: "Dashboard",
    nav_jobs: "Jobs",
    nav_logout: "Logout",
    nav_admin: "Admin",

    // ---- Home / Hero ----
    hero_title: "Myanmar Freelance Escrow",
    hero_subtitle: "A trusted platform for job matching and financial security",
    hero_tagline: "Secure escrow system for Freelancers and Hiring Managers",
    hero_cta_register: "Register Now",
    hero_cta_login: "Login",
    hero_how_title: "How It Works",
    hero_how_1: "Register and post a job or submit a proposal",
    hero_how_2: "Sign a digital contract",
    hero_how_3: "Fund escrow and start working",
    hero_how_4: "Milestone completed — funds released",
    hero_features_title: "Why Choose Us",
    hero_feature_1_title: "Escrow Security",
    hero_feature_1_desc: "Funds managed by Admin with protection for both parties",
    hero_feature_2_title: "Local Payments",
    hero_feature_2_desc: "KBZ Pay, Wave Pay, USDT and more local payment methods",
    hero_feature_3_title: "Myanmar Language",
    hero_feature_3_desc: "Full Myanmar language support built in",
    hero_feature_4_title: "Digital Contracts",
    hero_feature_4_desc: "Sign contracts with digital signatures",
    hero_stats_jobs: "Jobs",
    hero_stats_users: "Users",
    hero_stats_released: "Released",
    hero_stats_trust: "Trust",

    // ---- Auth ----
    auth_login_title: "Login",
    auth_register_title: "Register",
    auth_email: "Email",
    auth_password: "Password",
    auth_confirm_password: "Confirm Password",
    auth_name: "Full Name",
    auth_role_title: "Choose Your Role",
    auth_role_freelancer: "Provide Service (Freelancer)",
    auth_role_hiring: "Get Services (Hiring)",
    auth_role_freelancer_desc: "Work with your skills and earn money",
    auth_role_hiring_desc: "Hire Freelancers for your projects",
    auth_skill_level: "Skill Level",
    auth_skill_beginner: "Beginner",
    auth_skill_entry: "Entry",
    auth_skill_mid: "Mid-Level",
    auth_skill_advanced: "Advanced",
    auth_skill_pro: "Professional",
    auth_submit_login: "Login",
    auth_submit_register: "Register",
    auth_no_account: "Don't have an account?",
    auth_has_account: "Already have an account?",
    auth_role_locked_warning: "⚠️ Role cannot be changed after registration",
    auth_error_password_mismatch: "Passwords do not match",
    auth_error_weak_password: "Password too weak (min 6 characters)",
    auth_error_email_in_use: "Email already in use",
    auth_error_invalid_email: "Invalid email address",
    auth_error_user_not_found: "User not found",
    auth_error_wrong_password: "Wrong password",

    // ---- Dashboard ----
    dash_welcome: "Welcome",
    dash_freelancer_title: "Freelancer Dashboard",
    dash_hiring_title: "Hiring Dashboard",
    dash_my_proposals: "My Proposals",
    dash_active_contracts: "Active Contracts",
    dash_wallet: "Wallet",
    dash_balance: "Balance",
    dash_pending_withdrawals: "Pending Withdrawals",
    dash_posted_jobs: "Posted Jobs",
    dash_incoming_proposals: "Incoming Proposals",
    dash_manage_escrow: "Manage Escrow",
    dash_total_earned: "Total Earned",
    dash_total_spent: "Total Spent",
    dash_no_proposals: "No proposals yet",
    dash_no_contracts: "No contracts yet",
    dash_no_jobs: "No jobs posted yet",
    dash_view_details: "View Details",

    // ---- Jobs ----
    jobs_title: "Jobs",
    jobs_post_new: "Post New Job",
    jobs_search_placeholder: "Search jobs...",
    jobs_budget: "Budget",
    jobs_milestones: "Milestones",
    jobs_status_open: "Open",
    jobs_status_interviewing: "Interviewing",
    jobs_status_escrow_pending: "Escrow Pending",
    jobs_status_active: "Active",
    jobs_status_completed: "Completed",
    jobs_status_disputed: "Disputed",
    jobs_proposal_count: "Proposals",
    jobs_apply: "Apply",
    jobs_details: "Details",
    jobs_post_title: "Job Title",
    jobs_post_desc: "Detailed Description",
    jobs_post_budget: "Budget (MMK)",
    jobs_post_milestones: "Number of Milestones (max 5)",
    jobs_post_submit: "Post Job",
    jobs_post_cancel: "Cancel",
    jobs_proposal_bid: "Bid Amount (MMK)",
    jobs_proposal_cover: "Cover Letter",
    jobs_proposal_submit: "Submit Proposal",
    jobs_accept: "Accept",
    jobs_reject: "Reject",

    // ---- Escrow ----
    escrow_title: "Escrow Payment",
    escrow_select_milestone: "Select Milestone",
    escrow_amount: "Amount (MMK)",
    escrow_payment_method: "Payment Method",
    escrow_wallets: "Mobile Wallets",
    escrow_banks: "Banks",
    escrow_digital: "Digital Systems",
    escrow_kbz: "KBZ Pay",
    escrow_wave: "Wave Pay",
    escrow_aya_pay: "AYA Pay",
    escrow_cb_pay: "CB Pay",
    escrow_uab_pay: "UAB Pay",
    escrow_yoma: "Yoma Bank",
    escrow_aya_bank: "AYA Bank",
    escrow_kbz_bank: "KBZ Bank",
    escrow_cb_bank: "CB Bank",
    escrow_usdt: "USDT (TRC-20)",
    escrow_binance: "Binance Pay",
    escrow_djo: "DJO Pay",
    escrow_upload_proof: "Upload Transaction ID / Screenshot",
    escrow_submit_payment: "Confirm Payment",
    escrow_status_pending: "Pending",
    escrow_status_secured: "Secured",
    escrow_status_released: "Released",
    escrow_status_disputed: "Disputed",
    escrow_verify: "Admin Verify",
    escrow_file_placeholder: "Enter Transaction ID or upload screenshot",

    // ---- Contract ----
    contract_title: "Digital Contract",
    contract_job: "Job",
    contract_parties: "Parties",
    contract_client: "Hiring Manager",
    contract_freelancer: "Freelancer",
    contract_milestones_title: "Milestone Details",
    contract_sign: "Sign Contract",
    contract_sign_placeholder: "Type your full name",
    contract_sign_btn: "Sign Contract",
    contract_signed: "Signed",
    contract_awaiting_escrow: "Awaiting Escrow",
    contract_fully_signed: "Fully Signed by Both Parties",
    contract_not_signed: "Not Yet Signed",
    contract_sign_warning: "⚠️ Cannot be modified after signing",

    // ---- Workflow Status ----
    workflow_post: "Post",
    workflow_interview: "Interview",
    workflow_contract: "Contract",
    workflow_escrow: "Escrow",
    workflow_active: "Active",
    workflow_release: "Release",

    // ---- Admin ----
    admin_title: "Admin Dashboard",
    admin_overview: "Overview",
    admin_all_jobs: "All Jobs",
    admin_all_users: "All Users",
    admin_pending_verifications: "Pending Verifications",
    admin_disputes: "Disputes",
    admin_action: "Action",
    admin_unlock_milestone: "Unlock Milestone",
    admin_full_refund: "Full Refund to Client",
    admin_fifty_fifty: "50/50 Split",
    admin_full_release: "100% Release to Freelancer",
    admin_reset_job: "Reset Job to Open (Free)",
    admin_platform_fee: "Platform Fee",
    admin_fee_hiring: "Hiring: 1%",
    admin_fee_freelancer: "Freelancer: 2%",
    admin_total_revenue: "Total Revenue",

    // ---- Milestones ----
    milestone_title: "Milestone",
    milestone_status_pending: "Pending",
    milestone_status_escrowed: "Escrowed",
    milestone_status_released: "Released",
    milestone_status_disputed: "Disputed",
    milestone_amount: "Amount",
    milestone_progress: "Progress",

    // ---- General ----
    general_save: "Save",
    general_cancel: "Cancel",
    general_confirm: "Confirm",
    general_back: "Back",
    general_loading: "Loading...",
    general_no_data: "No data available",
    general_error: "An error occurred",
    general_success: "Success",
    general_close: "Close",
    general_language: "Language",
    general_myanmar: "မြန်မာ",
    general_english: "English",
    general_currency: "MMK",
    general_platform_name: "MM Escrow",
    general_version: "v1.0",
    general_made_with: "Built for Myanmar Freelancers",
    general_trust_badge: "🔒 Secure & Trusted",
  },
};

// Current language state
let currentLang = localStorage.getItem("mm_escrow_lang") || "my";

/**
 * Get a translated string by key
 * @param {string} key - Translation key
 * @returns {string} Translated string
 */
function t(key) {
  return (LANGUAGES[currentLang] && LANGUAGES[currentLang][key]) || key;
}

/**
 * Toggle between Burmese and English
 */
function toggleLanguage() {
  currentLang = currentLang === "my" ? "en" : "my";
  localStorage.setItem("mm_escrow_lang", currentLang);
  document.documentElement.lang = currentLang === "my" ? "my" : "en";
  // Re-render current view
  if (window.renderCurrentView) {
    window.renderCurrentView();
  }
}

/**
 * Get current language
 * @returns {string} 'my' or 'en'
 */
function getCurrentLang() {
  return currentLang;
}

export { t, toggleLanguage, getCurrentLang, LANGUAGES };
